import { useCallback, useEffect, useMemo, useState } from "react";
import { Edit3, Plus, Save, Settings2, Trash2, Wrench, X } from "lucide-react";
import { getErrorMessage } from "../../api/axiosClient";
import branchService, { type Branch } from "../../services/branchService";
import operationsService, { type BranchConfig, type BranchServiceAssignment, type WashService } from "../../services/operationsService";

function authUser(){try{return JSON.parse(localStorage.getItem("user")||"{}");}catch{return {};}}
const money=(v:number|string|null)=>v===null?"Theo giá gốc":`${Number(v).toLocaleString("vi-VN")} ₫`;
const defaults=(id:number):BranchConfig=>({BranchID:id,SlotDuration:30,TotalWashBays:1,BufferMinutes:5,MaxCarsPerBooking:1,CancelWindowHours:24});

export default function BranchOperations(){
 const user=authUser(); const manager=(user.role||user.Role)==="Manager"; const ownBranch=Number(user.branchId??user.BranchID)||0;
 const [branches,setBranches]=useState<Branch[]>([]); const [branchId,setBranchId]=useState(ownBranch); const [tab,setTab]=useState<"services"|"config">("services");
 const [services,setServices]=useState<WashService[]>([]); const [assigned,setAssigned]=useState<BranchServiceAssignment[]>([]); const [config,setConfig]=useState<BranchConfig>(defaults(ownBranch));
 const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [message,setMessage]=useState(""); const [open,setOpen]=useState(false); const [editing,setEditing]=useState<BranchServiceAssignment|null>(null);
 const [serviceId,setServiceId]=useState(0); const [override,setOverride]=useState(""); const [assignmentStatus,setAssignmentStatus]=useState<"Active"|"Inactive">("Active");
 const loadBase=useCallback(async()=>{try{const [b,s]=await Promise.all([branchService.getAllBranches(),operationsService.getServices({Status:"Active"})]);setBranches(b);setServices(s);if(!ownBranch&&b[0])setBranchId(b[0].BranchID);}catch(e){setMessage(getErrorMessage(e));}},[ownBranch]);
 useEffect(()=>{void Promise.resolve().then(loadBase);},[loadBase]);
 const loadBranch=useCallback(async()=>{if(!branchId)return;setLoading(true);setMessage("");try{const [a,c]=await Promise.all([operationsService.getBranchServices(branchId),operationsService.getBranchConfig(branchId)]);setAssigned(a);setConfig({...defaults(branchId),...c,BranchID:branchId});}catch(e){setMessage(getErrorMessage(e));}finally{setLoading(false);}},[branchId]);
 useEffect(()=>{void Promise.resolve().then(loadBranch);},[loadBranch]);
 const available=useMemo(()=>services.filter(s=>!assigned.some(a=>a.ServiceID===s.ServiceID)),[services,assigned]);
 function add(){setEditing(null);setServiceId(available[0]?.ServiceID||0);setOverride("");setAssignmentStatus("Active");setOpen(true);}
 function edit(a:BranchServiceAssignment){setEditing(a);setServiceId(a.ServiceID);setOverride(a.PriceOverride===null?"":String(a.PriceOverride));setAssignmentStatus(a.Status);setOpen(true);}
 async function submit(e:React.FormEvent){e.preventDefault();if(!branchId||!serviceId)return;setSaving(true);setMessage("");try{const price=override===""?null:Number(override);if(editing)await operationsService.updateBranchService(editing.BranchServiceID,{PriceOverride:price,Status:assignmentStatus});else await operationsService.assignBranchService({BranchID:branchId,ServiceID:serviceId,PriceOverride:price,Status:assignmentStatus});setOpen(false);await loadBranch();}catch(err){setMessage(getErrorMessage(err));}finally{setSaving(false);}}
 async function remove(a:BranchServiceAssignment){if(!window.confirm(`Ngừng cung cấp dịch vụ “${a.Services.ServiceName}” tại chi nhánh này?`))return;try{await operationsService.deleteBranchService(a.BranchServiceID);await loadBranch();}catch(e){setMessage(getErrorMessage(e));}}
 async function saveConfig(e:React.FormEvent){e.preventDefault();setSaving(true);setMessage("");try{await operationsService.saveBranchConfig(config);setMessage("Đã lưu cấu hình chi nhánh.");await loadBranch();}catch(err){setMessage(getErrorMessage(err));}finally{setSaving(false);}}
 return <div className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-2xl font-bold text-slate-900">Dịch vụ & cấu hình chi nhánh</h1><p className="mt-1 text-sm text-slate-500">Thiết lập giá bán và quy tắc vận hành.</p></div>{!manager&&<label className="text-sm font-medium">Chi nhánh<select value={branchId} onChange={e=>setBranchId(Number(e.target.value))} className="ml-2 rounded-lg border border-slate-200 px-3 py-2.5">{branches.map(b=><option key={b.BranchID} value={b.BranchID}>{b.BranchName}</option>)}</select></label>}</div>
 {message&&<div className={`rounded-lg border px-4 py-3 text-sm ${message.startsWith("Đã lưu")?"border-emerald-200 bg-emerald-50 text-emerald-700":"border-rose-200 bg-rose-50 text-rose-700"}`}>{message}</div>}
 <div className="flex gap-2 border-b border-slate-200"><button onClick={()=>setTab("services")} className={`flex items-center gap-2 border-b-2 px-4 py-3 font-medium ${tab==="services"?"border-sky-600 text-sky-700":"border-transparent text-slate-500"}`}><Wrench size={18}/>Dịch vụ tại chi nhánh</button><button onClick={()=>setTab("config")} className={`flex items-center gap-2 border-b-2 px-4 py-3 font-medium ${tab==="config"?"border-sky-600 text-sky-700":"border-transparent text-slate-500"}`}><Settings2 size={18}/>Cấu hình vận hành</button></div>
 {tab==="services"?<><div className="flex justify-end"><button onClick={add} disabled={!branchId||available.length===0} className="flex items-center gap-2 rounded-lg bg-sky-600 px-4 py-2.5 font-medium text-white disabled:opacity-50"><Plus size={18}/>Gán dịch vụ</button></div><div className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><table className="w-full text-left text-sm"><thead className="bg-slate-50"><tr><th className="px-5 py-3">Dịch vụ</th><th className="px-5 py-3">Giá gốc</th><th className="px-5 py-3">Giá chi nhánh</th><th className="px-5 py-3">Trạng thái</th><th className="px-5 py-3 text-right">Thao tác</th></tr></thead><tbody className="divide-y">{loading?<tr><td colSpan={5} className="py-12 text-center">Đang tải...</td></tr>:assigned.length===0?<tr><td colSpan={5} className="py-12 text-center text-slate-500">Chi nhánh chưa được gán dịch vụ.</td></tr>:assigned.map(a=><tr key={a.BranchServiceID}><td className="px-5 py-4 font-semibold">{a.Services.ServiceName}</td><td className="px-5 py-4">{money(a.Services.BasePrice)}</td><td className="px-5 py-4 font-medium text-sky-700">{money(a.PriceOverride)}</td><td className="px-5 py-4">{a.Status==="Active"?"Hoạt động":"Ngừng"}</td><td className="px-5 py-4"><div className="flex justify-end gap-2"><button onClick={()=>edit(a)} className="p-2 text-sky-600"><Edit3 size={17}/></button><button onClick={()=>void remove(a)} disabled={a.Status==="Inactive"} className="p-2 text-rose-600 disabled:opacity-30"><Trash2 size={17}/></button></div></td></tr>)}</tbody></table></div></>:
 <form onSubmit={saveConfig} className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{([['SlotDuration','Thời lượng mỗi slot','phút',1],['TotalWashBays','Tổng số bay rửa','bay',1],['BufferMinutes','Thời gian đệm','phút',0],['MaxCarsPerBooking','Số xe tối đa/booking','xe',1],['CancelWindowHours','Hạn hủy trước lịch','giờ',0]] as const).map(([key,label,unit,min])=><label key={key} className="text-sm font-medium text-slate-700">{label}<div className="mt-1 flex overflow-hidden rounded-lg border border-slate-200"><input required min={min} type="number" value={config[key]??0} onChange={e=>setConfig({...config,[key]:Number(e.target.value)})} className="min-w-0 flex-1 p-2.5 outline-none"/><span className="bg-slate-50 px-3 py-2.5 text-slate-500">{unit}</span></div></label>)}</div><p className="mt-5 text-sm text-amber-700">Lưu ý: BE sẽ từ chối đổi thời lượng slot hoặc thời gian đệm nếu chi nhánh đang có lịch tương lai.</p><div className="mt-6 flex justify-end"><button disabled={saving||!branchId} className="flex items-center gap-2 rounded-lg bg-sky-600 px-4 py-2.5 font-medium text-white disabled:opacity-50"><Save size={18}/>{saving?"Đang lưu...":"Lưu cấu hình"}</button></div></form>}
 {open&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/50 p-4"><form onSubmit={submit} className="w-full max-w-lg rounded-2xl bg-white p-6"><div className="mb-5 flex justify-between"><h2 className="text-xl font-bold">{editing?"Cập nhật dịch vụ":"Gán dịch vụ"}</h2><button type="button" onClick={()=>setOpen(false)}><X/></button></div><div className="space-y-4"><label className="block text-sm font-medium">Dịch vụ<select disabled={!!editing} value={serviceId} onChange={e=>setServiceId(Number(e.target.value))} className="mt-1 w-full rounded-lg border p-2.5">{(editing?services:available).map(s=><option key={s.ServiceID} value={s.ServiceID}>{s.ServiceName} — {money(s.BasePrice)}</option>)}</select></label><label className="block text-sm font-medium">Giá riêng (để trống để dùng giá gốc)<input min="1" type="number" value={override} onChange={e=>setOverride(e.target.value)} className="mt-1 w-full rounded-lg border p-2.5"/></label>{editing&&<label className="block text-sm font-medium">Trạng thái<select value={assignmentStatus} onChange={e=>setAssignmentStatus(e.target.value as "Active"|"Inactive")} className="mt-1 w-full rounded-lg border p-2.5"><option value="Active">Hoạt động</option><option value="Inactive">Ngừng</option></select></label>}</div><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={()=>setOpen(false)} className="rounded-lg border px-4 py-2">Hủy</button><button disabled={saving||!serviceId} className="rounded-lg bg-sky-600 px-4 py-2 text-white disabled:opacity-50">Lưu</button></div></form></div>}</div>;
}
